export const SAVE_USER_NUMBER = 'SAVE_USER_NUMBER';



export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAIL = 'USER_SIGN_IN_FAIL'
