export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_LOGGED_IN_REQUEST = 'USER_LOGGED_IN_REQUEST';
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_IN_FAIL = 'USER_LOGGED_IN_FAIL';

export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_CLEAN_UP = 'USER_CLEAN_UP'