export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_LOGGED_IN_REQUEST = 'USER_LOGGED_IN_REQUEST';
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_IN_FAIL = 'USER_LOGGED_IN_FAIL';

export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_CLEAN_UP = 'USER_CLEAN_UP'

export const USER_ANSWER_REQUEST = 'USER_ANSWER_REQUEST'
export const USER_ANSWER_CORRECT = 'USER_ANSWER_CORRECT';
export const USER_ANSWER_WRONG = 'USER_ANSWER_WRONG';
export const USER_ANSWER_RESET = 'USER_ANSWER_RESET'

export const ON_CURRENT_QUESTION = 'ON_CURRENT_QUESTION'
export const ON_NEXT_QUESTION = 'ON_NEXT_QUESTION'